...

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,9 +1,9 @@
-name: Create ALF File
+name: test
 
 on:
-  # push:
-  #   branches:
-  #     - '*'
+  push:
+    branches:
+      - '*'
 
   issues:
     types: [opened, reopened]
@@ -14,13 +14,15 @@ jobs:
   build:
 
     runs-on: ubuntu-latest
-    container: docker://gableroux/unity3d:${{ matrix.unity-version }}
-    strategy:
-      matrix:
-        unity-version: [2018.4.12f1]
+    # strategy:
+    #   matrix:
+    #     unity-version: [2018.4.12f1]
     
     steps:
-    # - uses: actions/checkout@v1
+    - uses: actions/checkout@v1
+    - uses: ./
+      with: 
+        unity-version: 2018.4.12f1
 
     # - name: Cache Unity License File
     #   id: cache
@@ -42,43 +44,43 @@ jobs:
     #     ULF_2018: ${{ secrets.ULF_2018 }}
     
 
-    - name: Unity
-      run: |
-        set -x
-        set +e
-        apt -y update
-        apt -y install jq
+    # - name: Unity
+    #   run: |
+    #     set -x
+    #     set +e
+    #     apt -y update
+    #     apt -y install jq
 
-        NAME=ULF_`echo ${{ matrix.unity-version }} | tr '.' '\n' | head -n 1`
-        JSON=$(cat << EOS
-        ${{ toJson(secrets) }}
-        EOS
-        )
+    #     NAME=ULF_`echo ${{ matrix.unity-version }} | tr '.' '\n' | head -n 1`
+    #     JSON=$(cat << EOS
+    #     ${{ toJson(secrets) }}
+    #     EOS
+    #     )
 
-        ULF=`echo $JSON | jq .$NAME`
-        if [[ "$NAME" != "null" ]]; then
-          echo $NAME
-        fi
-        if [[ "$ULF" != "null" ]]; then
-          echo "$NAME あるで"
-          echo $ULF > temp.ulf
-          /opt/Unity/Editor/Unity -manualLicenseFile temp.ulf -batchmode -nographics -quit
-          echo "ライセンス有効化しといたで"
-          exit 0
-        else
-          echo "$NAME ないで"
-          /opt/Unity/Editor/Unity -quit -batchmode -nographics -logfile -createManualActivationFile
-          mkdir .alf && mv Unity_v${{ matrix.unity-version }}.alf .alf
-          echo "ALF吐き出しといた。artifactsからダウンロードして、手動でulfに変換、secretsに追加してクレメンス！"
-          exit 1
-        fi
+    #     ULF=`echo $JSON | jq .$NAME`
+    #     if [[ "$NAME" != "null" ]]; then
+    #       echo $NAME
+    #     fi
+    #     if [[ "$ULF" != "null" ]]; then
+    #       echo "$NAME あるで"
+    #       echo $ULF > temp.ulf
+    #       /opt/Unity/Editor/Unity -manualLicenseFile temp.ulf -batchmode -nographics -quit
+    #       echo "ライセンス有効化しといたで"
+    #       exit 0
+    #     else
+    #       echo "$NAME ないで"
+    #       /opt/Unity/Editor/Unity -quit -batchmode -nographics -logfile -createManualActivationFile
+    #       mkdir .alf && mv Unity_v${{ matrix.unity-version }}.alf .alf
+    #       echo "ALF吐き出しといた。artifactsからダウンロードして、手動でulfに変換、secretsに追加してクレメンス！"
+    #       exit 1
+    #     fi
 
-    - name: (OPTION)upload-alf
-      if: failure()
-      uses: actions/upload-artifact@v1
-      with:
-        name: Unity_v${{ matrix.unity-version }}.alf
-        path: .alf
+    # - name: (OPTION)upload-alf
+    #   if: failure()
+    #   uses: actions/upload-artifact@v1
+    #   with:
+    #     name: Unity_v${{ matrix.unity-version }}.alf
+    #     path: .alf
 
     # - name: ULF_2018
     #   if: secrets.ULF_2018 != 0
